output_path = "/data/projects/rory_says_hi/readfish_update_paper"
target_yield = 100000000000
working_pore_percent = 80
pore_type = "R10"
nucleotide_type = "DNA"

[parameters]
sample_name = "human_barcoded"
experiment_name = "test_timings_grid_builtin"
flowcell_name = "PAS000000"
experiment_duration_set = 120
device_id = "Bantersaurus"
position = "FenceSitter"
sample_rate = 5000
break_read_ms = 800

[[sample]]
name = "Bacteria 1"
input_genome = "/squiggle_arrs/hg38_chr20.fa.gz"
#input_genome = "/data/refs/hg38.p14.simple.fa"
#input_genome = "/data/projects/rory_says_hi/Icarust/docker/squiggle_arrs/mixed_ref.fa"
mean_read_length = 10000
weight = 1
barcodes = ["Barcode01", "Barcode02", "Barcode03"]
barcode_weights = [1, 2, 1]
